package community.community.mapper;

import community.community.dto.QuestionDTO;
import community.community.dto.QuestionQueryDTO;
import community.community.model.Question;
import community.community.model.QuestionExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface QuestionExtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUESTION
     *
     * @mbg.generated Mon Oct 09 10:25:17 CST 2023
     */
    int incView(Question row);

    void incCommentCount(Question question);
    List<Question> selectRelated(Question question);

    Integer countBySearch(QuestionQueryDTO questionQueryDTO);

    List<Question> selectBySearch(QuestionQueryDTO questionQueryDTO);
}